### ISSUE TITLE
How should  I validate dynamic properties with known properties

### ISSUE THREAD

**Issue by oalexoprea** [Julian/jsonschema#552]
Hi
I have this data:

> 

```
---
servers:
  srv1:
    location: local
    dmz: True
    environment: prod
  srv2:
    location: local
    dmz: True
    environment: prod
.
.
.
.

```

and the schema looks like this:

```
type: object
additionalProperties: false
properties:
  servers:
    type: object
    patternProperties:
        '^[a-zA-Z0-9]*$':
          type: object
          additionalProperties: false                
          properties:
            location:
              type: string
            dmz:
              type: string
            environment:
              type: string
          required: ["location","dmz","environment"]
required: ["servers"]
```

I don't know if I'm on the right path, can you please help?
